### ISSUE TITLE
Viewpoint centerOfRotation

### ISSUE THREAD

**Issue by andreasplesch** [jamesleesaunders/d3-x3dom#11]
The charts look really nice, congratulations.
The Viewpoint centerOfRotation seems to be always at the origin. Placing it at the center of the data and chart would be more comfortable.

**Comment by jamesleesaunders** [comment]
Great idea! I’ll have a play with contre of rotation.
I think you may be right, the centre of the chart may work better.

**Comment by jamesleesaunders** [comment]
Done! Moving center of rotation to the centre of the chart does indeed make it more comfortable. Thanks for the suggestion.
