### ISSUE TITLE
Other chart ideas

### ISSUE THREAD

**Issue by andreasplesch** [jamesleesaunders/d3-x3dom#12]
Cylinders instead of bars
Configurable markers for scatter plot: boxes .., or even custom IFS
Pie chart
...

**Comment by jamesleesaunders** [comment]
https://goo.gl/images/zek2UY

**Comment by jamesleesaunders** [comment]
https://goo.gl/images/JEE6cL

**Comment by jamesleesaunders** [comment]
Thanks @andreasplesch 
I will look to make a cylinder version of the bar chart - that would be easy!
The ticks on the axis are now customisable.
What is a 'IFS'?

**Comment by andreasplesch** [comment]
Sorry, IFS is sometimes used for IndexedFaceSet, so arbitrary geometry.
