### ISSUE TITLE
Fix class names in documentation

### ISSUE THREAD

**Issue by Glinkis** [jamesleesaunders/d3-x3dom#28]
All classes in the docs are currently named `my`.
This is kind of confusing.

**Comment by jamesleesaunders** [comment]
@Glinkis I have had a little go at fixing this in branch https://github.com/jamesleesaunders/d3-x3dom/tree/jsdoc-fixes
I have used the @alias tag which has kind of worked.
However to be honest I am not 100% sure I should/not be using the @constructor tag in this sort of d3 module pattern.

Links in my research so far...
* http://usejsdoc.org/tags-alias.html
* https://stackoverflow.com/questions/50451305/documentationjs-how-to-document-closures-instance-variables-and-static-members
* http://usejsdoc.org/tags-module.html

BTW HUUUUUGE Thanks for getting the JSDoc module implemented, you are being a massive help (and helping me learn!).
