### ISSUE TITLE
Using default imports.

### ISSUE THREAD

**Issue by Glinkis** [jamesleesaunders/d3-x3dom#33]
Modules are currently imported as
`import { default as chartSurfaceArea } from "./chart/surfaceArea";`
Which are more commonly expressed as
`import chartSurfaceArea from "./chart/surfaceArea";`
or
`import * as chartSurfaceArea from "./chart/surfaceArea";`

And `{ default as name }` tends to make for a double take when reading.

I know this is very subjective, so feel free to close this issue if you think it's not needed.

**Comment by jamesleesaunders** [comment]
Cheers dude,
I have gone with `import chartSurfaceArea from "./chart/surfaceArea";`
:-)
