### ISSUE TITLE
New 'Vector Fields' component

### ISSUE THREAD

**Issue by jamesleesaunders** [jamesleesaunders/d3-x3dom#47]
### Summary

Create new 'Vector Fields' d3-x3d reusable component. Arrows representing flow direction. Also known as Quiver Plot or Velocity Plot.

### Detail

Vector fields have many important applications, as they can be used to represent many physical quantities: the vector at a point may represent the strength of some force (gravity, electricity, magnetism) or a velocity (wind speed or the velocity of some other fluid).

### Examples

* https://mathinsight.org/vector_field_overview
* https://goo.gl/images/WTSRZq
* https://goo.gl/images/zek2UY
* https://github.com/mjkaufer/3DVectorFields/
* http://bl.ocks.org/adrianturcato/cf665b7cca9f6057691a

### Relevant Files

`/src/component/vectorFields.js`
`/src/chart/vectorFieldChart.js`

**Comment by jamesleesaunders** [comment]
http://onedayitwillmake.com/blog/2011/09/getting-the-angle-between-two-3d-points/

**Comment by jamesleesaunders** [comment]
@andreasplesch @JordanDelcros are you able to help me with a problem? I am trying to calculate the yaw, pitch and roll rotation angles needed to rotate a vector arrow between 2 points.

Using x3dom and Vector3 libraries.

I have put my attempts at vector calculations up on Observable here https://beta.observablehq.com/@jamesleesaunders/vector-fields but now all confused.

Any ideas?

**Comment by andreasplesch** [comment]
x3dom has a quaternion.rotateFromTo method to get the rotation,
quaternion.toMatrix to convert and a matrix4f.getEulerAngles method to
extract Euler angles.

Hope this helps, Andreas

---on the phone---

**Comment by jamesleesaunders** [comment]
Thanks @andreasplesch those methods look right up my street!
I'll have a play!
```
var point1 = new x3dom.fields.SFVec3f(1, 1, 1);
var point2 = new x3dom.fields.SFVec3f(2, 2, 2);
var qDir = x3dom.fields.Quaternion.rotateFromTo(point1, point2);
var rot = qDir.toAxisAngle();
```

**Comment by jamesleesaunders** [comment]
Last few niggles:
* Component example.
* If scale > 0 crosshair axis funny.
* If vector coordinate numbers infinite then things go wrong.

**Comment by jamesleesaunders** [comment]
https://www.geogebra.org/m/KKB2Ndez

**Comment by jamesleesaunders** [comment]
https://mathematica.stackexchange.com/questions/110397/plotting-a-3d-vector-field-on-2d-plane

**Comment by jamesleesaunders** [comment]
https://math.stackexchange.com/questions/2870805/why-is-the-curl-of-a-function-which-looks-like-a-vortex-zero
