### ISSUE TITLE
links broken on this page

### ISSUE THREAD

**Issue by oli1230** [jamesleesaunders/d3-x3dom#75]
https://jamesleesaunders.github.io/d3-x3dom/#examples

**Comment by jamesleesaunders** [comment]
Thanks for highlighting.
I'll try and fix. This is caused by the JSDoc auto generation not correctly generating anchor links (they just jump down to the title further down the page).

In the mean time these links work on:
https://github.com/jamesleesaunders/d3-x3dom/blob/master/README.md
