### ISSUE TITLE
Due to a bug in x3dom, we must to use .html() rather than .append() & .attr()

### ISSUE THREAD

**Issue by jamesleesaunders** [jamesleesaunders/d3-x3dom#84]
Due to a bug in x3dom Shape/IndexFaceset, we must to use D3 .html() rather than .append() & .attr().

Rather than use `.append()` & `.attr()`:
```
shape.append("IndexedFaceset")
	.attr("coordIndex", (d) => d.coordIndex)
	.append("Coordinate")
	.attr("point", (d) => d.point);

shape.append("Appearance")
	.append("Material")
	.attr("diffuseColor", color)
	.attr("transparency", transparency);
```
We have to use `.html()` to manually build the innerHTML:
```
shape.html((d) => `
	<IndexedFaceset coordIndex="${d.coordIndex}" solid="false">
		<Coordinate point="${d.point}"></Coordinate>
	</IndexedFaceset>
	<Appearance>
		<Material diffuseColor="${color}" transparency="${transparency}"></Material>
	</Appearance>
`);
```

It would be preferable to be able to follow standard D3 patterns with `.append()` & `.attr()`.

### Files

**IndexedFaceSet**
https://github.com/jamesleesaunders/d3-x3dom/blob/70e3d7d84442d29b3b1ecb19b32c5b78df44d101/src/component/area.js#L103-L129
https://github.com/jamesleesaunders/d3-x3dom/blob/70e3d7d84442d29b3b1ecb19b32c5b78df44d101/src/component/ribbon.js#L121-L153

**Cylinder**
https://github.com/jamesleesaunders/d3-x3dom/blob/70e3d7d84442d29b3b1ecb19b32c5b78df44d101/src/component/axis.js#L94-L116

**Comment by jamesleesaunders** [comment]
A similar x3dom issue for sphere transition was resolved by PR https://github.com/x3dom/x3dom/pull/949

**Comment by jamesleesaunders** [comment]
Email comms with @andreasplesch on the x3dom-users mailing list:
https://sourceforge.net/p/x3dom/mailman/x3dom-users/?viewmonth=201904&viewday=5

> It is a subtle bug in x3dom which does not get exposed until a series
> of things happen.
> 
> This uses a slightly modified bubbles component which creates the
> sphere node in one step instead of two. This uses selection.html() to
> create the node with its attributes in one step. It is not recommended
> by d3 (although I am not quite sure why). It would be better to first
> create a detached Sphere node, then set its radius attribute, and only
> then append it to the Shape node. But it could not figure out how to
> do that with d3 selections. innerHTML does that in effect and seems to
> work well. This is not just a workaround but is also more efficient
> since it avoids multiple dom and therefore x3d graph mutations.
> 
> Here is the bug which I think can be fixed. The oversight is that
> sometimes a spherenode._quality property does not get created. If it
> does not exists, fieldChanged(radius) does not work and mesh positions
> do not get created. ._quality does not created if usegeocache is
> enabled (the default) and a sphere with the same mesh has been created
> before and cached. This works but only if there is one such sphere
> with such a geometry (radius plus subdivisions). If there are two or
> more the second such sphere also the cached mesh but its ._quality
> property does not get created. This is still not a problem until
> fieldChanged() gets called. Then the mesh needs to change but fails
> because of the missing property.
> 
> For the ribbons, the issue appears to be that the indexedfaceset gets
> initially created without a or with an empty coordnode. It smells like
> it could also be addressed by first creating a detached indexedfaceset
> node and only when it is complete to append it to the shape node.

**Comment by andreasplesch** [comment]
Adding a bit more background, let me point to the soec. signature of IFS: mm

http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/geometry3D.html#IndexedFaceSet

The fields, eg. attributes, have a data type and event types. The fields with an 'in' event type can receive events, eg. be modified after initialization. Others cannot, for simplicity and player performance. This is why it does not always work to first create a node, and then update an attribute.

So strictly speaking x3dom just conforms to the spec. On the other hand, the only real obstacle is that the required code is a bit complex and would require a significant effort.

So better for now to stick with x3d compliance by using d3.html .

**Comment by jamesleesaunders** [comment]
@andreasplesch Thanks!

Ahha I see, so for **IndexedFaceSet** is is 'coordIndex' in particular which I am trying to update, but does not have 'in':
```
IndexedFaceSet : X3DComposedGeometryNode {
  MFInt32 [in]     set_colorIndex
  MFInt32 [in]     set_coordIndex
  MFInt32 [in]     set_normalIndex
  MFInt32 [in]     set_texCoordIndex
  MFNode  [in,out] attrib            []   [X3DVertexAttributeNode]
  SFNode  [in,out] color             NULL [X3DColorNode]
  SFNode  [in,out] coord             NULL [X3DCoordinateNode]
  SFNode  [in,out] fogCoord          NULL [FogCoordinate]
  SFNode  [in,out] metadata          NULL [X3DMetadataObject]
  SFNode  [in,out] normal            NULL [X3DNormalNode]
  SFNode  [in,out] texCoord          NULL [X3DTextureCoordinateNode]
  SFBool  []       ccw               TRUE
  MFInt32 []       colorIndex        []   [0,∞) or -1
  SFBool  []       colorPerVertex    TRUE
  SFBool  []       convex            TRUE
  MFInt32 []       coordIndex        []   [0,∞) or -1
  SFFloat []       creaseAngle       0    [0,∞)
  MFInt32 []       normalIndex       []   [0,∞) or -1
  SFBool  []       normalPerVertex   TRUE
  SFBool  []       solid             TRUE
  MFInt32 []       texCoordIndex     []   [-1,∞)
}
```

and for **Cylinder** it is `radius` and `height` which I am trying to update, but does not have 'in':
```
Cylinder : X3DGeometryNode { 
  SFNode  [in,out] metadata NULL [X3DMetadataObject]
  SFBool  []       bottom   TRUE
  SFFloat []       height   2    (0,∞)
  SFFloat []       radius   1    (0,∞)
  SFBool  []       side     TRUE
  SFBool  []       solid    TRUE
  SFBool  []       top      TRUE
}
```

Did we slightly bend the spec for **Sphere** (https://github.com/x3dom/x3dom/pull/949) for `radius` which strictly speaking also does not have 'in':
```
Sphere : X3DGeometryNode { 
  SFNode  [in,out] metadata NULL [X3DMetadataObject]
  SFFloat []       radius   1    (0,∞)
  SFBool  []       solid    TRUE
}
```

I guess if this is the spec then it sounds like I will not be able to swap out the d3.html. I will investigate the detached node once more, but it sounds like I may just have to live with it :-) It is not a massive problem, it just rubs my OCD up the wrong way not being able to follow standard D3 practice (something I will have to live with straddling the D3 and X3DOM realms).

**Comment by jamesleesaunders** [comment]
Interestingly I am using **Box** for the the bar chart component and changing its `size` in transition but this is not a problem, but this also does not have 'in':
```
Box : X3DGeometryNode { 
  SFNode  [in,out] metadata NULL  [X3DMetadataObject]
  SFVec3f []       size     2 2 2 (0,∞)
  SFBool  []       solid    TRUE
}
```

https://github.com/jamesleesaunders/d3-x3dom/blob/70e3d7d84442d29b3b1ecb19b32c5b78df44d101/src/component/bars.js#L68-L86

**Comment by andreasplesch** [comment]
For Box and Sphere it is relatively straightforward to allow dynamic changes. IFS coordIndex changes require completely replacing the mesh, so it really is almost the same as replacing the whole node.

**Comment by jamesleesaunders** [comment]
If not for IFS, do you think it would be easier (and appropriate) to add it to Cylinder? This could be a good little challenge for me to dip further into x3dom and create a PR.

**Comment by andreasplesch** [comment]
For Cylinder, radius and height changes are already recognized in fieldChanged(), going beyond the spec.

It does not work ?

**Comment by jamesleesaunders** [comment]
Interesting, there is some kind of glitchyness going on with Cylinder. 

I have created a branch where I have reversed the .html() & .append()/.attr() in axis.js which displays the issue. See https://github.com/jamesleesaunders/d3-x3dom/commit/fe431da3a27b533c4390e409a38e26629f940b03 for the diff.

Examples:
https://raw.githack.com/jamesleesaunders/d3-x3dom/issue-84/examples/chart/BarChartVertical.html
or:
https://raw.githack.com/jamesleesaunders/d3-x3dom/issue-84/examples/chart/AreaChartMultiSeries.html

On either of the above if you tick and un-tick some of the series to make the scales re-calculate (you sometimes need to refresh a couple of times to get a suitable random dataset which has different series highs and lows to show the issue). You see sometime axis tick bars sometime get left behind or are the wrong length.

Unless I am hitting some other bug?

**Comment by andreasplesch** [comment]
I used 
https://raw.githack.com/jamesleesaunders/d3-x3dom/issue-84/examples/chart/BarChartVertical.html
to investigate.
Switching off and then on the largest bar reliably generates the very long tick. This seems like a good test case.
Using the debugger on fieldChanged in Cylinder.js I noticed that it actually gets called with a large height (40). A break point in d3-x3dom where the cylinder element is appended and then gets its attributes modified shows that actually height attribute value is set to 40.
For some reason this does not get reflected in the html. Is it reset to 0 but not picked up then by x3dom ?

**Comment by andreasplesch** [comment]
ok, I think the problem is the use of the mesh cache by the default usegeocache=true field. Disabling the cache fixes the issue.

What happens is that the tick cylinder get created with default values, and cached mesh is used directly without copying. Then later this mesh object get modified with a height=40 for the horizontal bars, but is then used for the vertical tick since it is the same object.

The problem is the cache can only be disabled at inital node creation, and by default it is on.

So the proper fix is to be more careful with the cache, or perhaps disable it by default in X3DGeometryNode.js

It is not a problem with the .html method because there the mesh is not modified.

**Comment by jamesleesaunders** [comment]
Thanks again @andreasplesch I has a suspicion it was ‘artefacts’ being left behind from another axis and there was some weird caching going on, but I had no idea really.

I am happy to stick with the .html method for now, but do you think this is a bug which should be raised on x3dom, of course I appreciate this is a weird corner case (and not really part of spec) so I can understand if you think it is not something to worry about. I guess this is just what I get from being on the bleeding edge between d3 and x3dom.

My only thoughts are if/when another d3 developer takes a shine to x3dom who is used to transitions on svg, they may hit the same glitches as me and may end up banging head on walls like me for a while until they realise the reasons.

I would love to have a go at fixing this myself but you may need to give me some guidance as to what to change in x3dom code. 

Thanks again!

**Comment by andreasplesch** [comment]
Yes, it would be a more general issue, and would require a larger effort to fix properly. See https://github.com/x3dom/x3dom/issues/967.

What occurred to me for this case, is that you could use the cache (the default) if you do not change the default Cylinder but instead scale it in the wrapper transform: scale="radius height 1"

But it is simpler to use the .html solution.

Or d3.create : https://github.com/d3/d3-selection/blob/master/README.md#create

**Comment by andreasplesch** [comment]
I finally figured out how to use d3.create:

```js
// FIXME: Due to a bug in x3dom, we must to use .html() rather than .append() & .attr().
// shape.append("Cylinder").attr("radius", radius).attr("height", height);
// shape.append("Appearance").append("Material").attr("diffuseColor", color);
shape.append( function createCylinder() {
	return d3.create("Cylinder").attr("radius", radius).attr("height", height).node() });
shape.append( function createApp() {
	return (d3.create("Appearance").append("Material").attr("diffuseColor", color)).node() });
```

The main idea is to use d3.create inside the callback to make sure that a new element is created for each passed in shape node. I had it outside first, so only one tick was created and moved around by appending to subsequent Shapes.

This creates first a detached node, populates it with the attributes, and then appends the fully populated node to Shape. This avoids unnecessary page updates (and should be more efficient with typical svg use as well) and may be more d3 like. I think this would be a good overall pattern along with the html which has its own advantages.

**Comment by jamesleesaunders** [comment]
Cool! I too was playing (head scratching) with .create() last night getting confused. I'm glad you figured it out. That is another good one to add to my d3 armoury.
I will have a play with this tomorrow on the IFS examples (area.js and ribbon.js).

And for cylinder (axis.js) we will hopefully have that one fixed with the useGeoCache toggle option.

**Comment by andreasplesch** [comment]
It is also possible to construct the full Shape node detached, and then append as in:
```js
		var shape = function shape(el, radius, height, color) {
			el.append( function() {
				var shape = d3.create("Shape");
				shape.append("Cylinder").attr("height", height).attr("radius", radius);
				shape.append("Appearance").append("Material").attr("diffuseColor", color);
				return shape.node();
			});
			return
		
			/*
         shape.html(() => `
    	<Cylinder radius="${radius}" height="${height}"></Cylinder>
    	<Appearance>
    		<Material diffuseColor="${color}"></Material>
    	</Appearance>
         `);
          */
			
		};
```
I think that looks a little better.
